### ISSUE TITLE
Metrics are not captured for requests routed using app.use(path, handlers)

### ISSUE THREAD

**Issue by lewisvail3** [DataDog/node-connect-datadog#5]
When routing requests using `app.use(path, handlers)`, the `req.route` object is not set and so metrics are not reported for those requests.  Below is an example route that you may want metrics for which currently doesn't work:

```
var proxy = require('express-http-proxy');
var app = require('express')();
 
app.use('/proxy', proxy('www.google.com'));
```

**Comment by lewisvail3** [comment]
This issue appears to duplicate one opened against the original git repo: https://github.com/AppPress/node-connect-datadog/issues/10

**Comment by rochdev** [comment]
`app.use()` is part of the middleware API and is not related to routing. Can you try with `app.all()` instead?

**Comment by lewisvail3** [comment]
This bug should be fixed by https://github.com/DataDog/node-connect-datadog/pull/8

**Comment by rochdev** [comment]
I misunderstood the issue. I thought it meant that metrics are reported but without a route tag when you were actually meaning that it was not reported at all.

Should this be closed then?

**Comment by lewisvail3** [comment]
Yes, closing now.
